spring.application.name=demo
# ตั้งค่าเชื่อมต่อ MySQL
spring.datasource.url=mysql://root:OBvHVTAKzegkhJrTZdbZofqroNUFlbJx@mysql.railway.internal:3306/railway
spring.datasource.username=root
# เปลี่ยนรหัสผ่านตรงนี้เป็นรหัสผ่าน MySQL ของคุณ
spring.datasource.password=OBvHVTAKzegkhJrTZdbZofqroNUFlbJx

# ให้ Hibernate สร้าง/อัปเดตตารางให้โดยอัตโนมัติ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ตั้งค่า Thymeleaf ไม่ให้แคช (จะได้เห็นการเปลี่ยนแปลงทันทีตอนแก้หน้าเว็บ)
spring.thymeleaf.cache=false