spring.application.name=demo
server.port=${PORT:8080}

# เปลี่ยนเป็น jdbc:mysql:// และลบ user:pass ออกจาก URL
spring.datasource.url=jdbc:mysql://library-db-book.j.aivencloud.com:26588/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VMW_xpVvjuH9ZYr2rXe

# ให้ Hibernate สร้าง/อัปเดตตารางให้โดยอัตโนมัติ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false